# Check out https://docs.codemagic.io/getting-started/building-a-react-native-app/ for more information
# Please review and update values in curly braces

workflows:
    react-native:
        name: React Native App
        environment:
            vars:
                XCODE_WORKSPACE: "appconverter.xcodeproj"
                XCODE_SCHEME: "appconverter"
                APP_NAME: "app"
            node: latest
        scripts:


            - for i in 1..3
            - do
            - echo $i
            - done
            - npm install node-jq
            - jq -r '.app_name' build_data/data.json
            - for i in 1..jq -r '.permission|length' build_data/data.json
                do
                sed -i '4i  <uses-permission android:name=$(jq jq -r '.permissions[$i]' build_data/data.json ) />'
                done
            - sed -i "s/appconverter/$(jq -r '.app_name' build_data/data.json)/g" android/app/src/main/res/values/strings.xml
            - cp build_data/ic_launcher.png android/app/src/main/res/drawable
            - npm ins1tall            
            - echo "sdk.dir=$HOME/programs/android-sdk-macosx" > "$FCI_BUILD_DIR/android/local.properties"
            - |
                # build Android
                cd android
                ./gradlew assembleRelease
           
        artifacts:
            - android/app/build/outputs/**/*.apk
           