# Check out https://docs.codemagic.io/getting-started/building-a-react-native-app/ for more information
# Please review and update values in curly braces

workflows:
    react-native:
        name: React Native App
        environment:
            vars:
                XCODE_WORKSPACE: "appconverter.xcodeproj"
                XCODE_SCHEME: "appconverter"
                APP_NAME: "app"
            node: latest
        scripts:




            - brew install jq
           
            - for i in $(seq 0 $(jq -r '.permissions|length-1' build_data/data.json));
                do sed -i "" -e $'4 a\\\n'" <uses-permission android:name="android.permissions.$(jq -r ".permissions[$i]" build_data/data.json)" />" android/app/src/main/AndroidManifest.xml;
                done
            - cat android/app/src/main/AndroidManifest.xml
            - for i in $(seq 0 $(jq -r ".permissions_IOS|length-1" build_data/data.json));
                do echo $i;echo $(jq -r "permissions_IOS[0]" build_data/data.json);
                done
 
            
            - cat ios/appconverter/info.plist
            - jq -r '.appname' build_data/data.json
            - sed -i "" "s/appconverter/$(jq -r '.appname' build_data/data.json)/g" android/app/src/main/res/values/strings.xml
            - cat android/app/src/main/res/values/strings.xml
            - cp build_data/ic_launcher.png android/app/src/main/res/drawable
            - npm ins1tall            
            - echo "sdk.dir=$HOME/programs/android-sdk-macosx" > "$FCI_BUILD_DIR/android/local.properties"
            - |
                # build Android
                cd android
                ./gradlew assembleRelease
           
        artifacts:
            - android/app/build/outputs/**/*.apk
           