# Check out https://docs.codemagic.io/getting-started/building-a-react-native-app/ for more information
# Please review and update values in curly braces

workflows:
    react-native:
        name: React Native App
        environment:
            vars:
                XCODE_WORKSPACE: "appconverter.xcodeproj"
                XCODE_SCHEME: "appconverter"
                APP_NAME: "app"
            node: latest
        scripts:

            
            
            - sed 's/appconverter/`node -pe 'JSON.parse(process.argv[1]).url' 
            $(cat build_data/data.json)`/' android/app/src/main/res/values/strings.xml
           
            - npm install node-jq
            - jq build_data/data.json
            
            - cp build_data/ic_launcher.png android/app/src/main/res/drawable
            - npm install            
            - echo "sdk.dir=$HOME/programs/android-sdk-macosx" > "$FCI_BUILD_DIR/android/local.properties"
            - |
                # build Android
                cd android
                ./gradlew assembleRelease
           
        artifacts:
            - android/app/build/outputs/**/*.apk
           